name: techamp_flutter_shopping_app
description: A new Flutter project.

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  auto_route: ^0.6.9
  flutter:
    sdk: flutter
  bloc: ^6.1.1
  dio: ^3.0.10
  flutter_bloc: ^6.1.2
  get_it: ^5.0.6

dev_dependencies:
  auto_route_generator: ^0.6.10
  build_runner: ^1.11.1
  flutter_test:
    sdk: flutter
  bloc_test: ^7.1.0
  mockito: ^4.1.4

flutter:
  uses-material-design: true
