name: techamp_flutter_shopping_app
description: A new Flutter project.

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^0.6.9
  bloc: ^6.1.1
  dio: ^3.0.10
  flutter_bloc: ^6.1.2
  freezed_annotation: ^0.12.0
  get_it: ^5.0.6
  hydrated_bloc: ^6.1.0
  json_annotation: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.6.10
  bloc_test: ^7.1.0
  build_runner: ^1.11.1
  freezed: ^0.12.7
  json_serializable: ^3.5.1
  mockito: ^4.1.4

flutter:
  uses-material-design: true
